{{/*
NodePort Service for Dagster Webserver

Provides reliable external access to the Dagster UI on a fixed NodePort.
The Dagster subchart only supports ClusterIP, so we create an additional
NodePort service that routes to the same pods.

Access via: http://localhost:{{ .Values.localAccess.nodePort }} on Docker Desktop
*/}}
{{- if and .Values.localAccess .Values.localAccess.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dagster-webserver-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "floe-dagster.labels" . | nindent 4 }}
    app.kubernetes.io/component: webserver-nodeport
  annotations:
    description: "NodePort access to Dagster Webserver UI"
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: {{ .Values.localAccess.nodePort | default 30000 }}
      protocol: TCP
  selector:
    # Match the Dagster subchart's webserver pods
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: dagster
    component: dagster-webserver
{{- end }}
